### ISSUE TITLE
Security issue: LDAP injection

### ISSUE THREAD

**Issue by cFire** [commercehub-oss/ssh-ca-server#2]
Hello,

During a code review of this project we have discovered an LDAP injection issue. Can you please provide us with a contact email where we may submit details without making them public just yet?

**Comment by davidmc24** [comment]
Thank you for reaching out.  Please send the details to oss-security@commercehub.com.

**Comment by cFire** [comment]
Thanks. I've submitted the bug report to the provided email address.

**Comment by davidmc24** [comment]
Thank you again for the report.  Fix released in version 0.1.3.
