### ISSUE TITLE
Getting 500 Internal Server Error when trying to list Roles

### ISSUE THREAD

**Issue by maxr786** [commercehub-oss/ssh-ca-server#5]
Hello,
I was wondering if could help me with the issue I am having when listing roles. The server log lists the LDAP group however the HTTP get shows 500 Internal Server Error. Service logs show the following: 
rv = self.dispatch_request()
File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python2.7/site-packages/ssh_ca_server/views.py", line 88, in list_roles
if ldap.is_member(requested_username, ldap_group):
File "/usr/lib/python2.7/site-packages/ssh_ca_server/ldapclient.py", line 98, in is_member
user_name = self.sanitizeLDAP(user_name)
File "/usr/lib/python2.7/site-packages/ssh_ca_server/ldapclient.py", line 87, in sanitizeLDAP
return ldap_string.replace("\\","\\5c")\
AttributeError: 'NoneType' object has no attribute 'replace'

Appreciate any help.

**Comment by aheiss1** [comment]
What's the user_name look like?

**Comment by maxr786** [comment]
Hi,
Thank you for your reply. I was able to solve that issue by changing the base_dn. Now I am running into a new issue. When I curl the sign my public key, I get 500 Internal server error. Logs say below: 
allowed_principals = ldap.get_authorized_principals(username, requested_ca)
File "/usr/lib/python2.7/site-packages/ssh_ca_server/ldapclient.py", line 201, in get_authorized_principals
allowed_cas = role['allowed_cas'].split(',')
AttributeError: 'list' object has no attribute 'split'

What is it mean by that?

**Comment by maxr786** [comment]
Is it because I am using a multivalued attribute instead of comma-delimited for ca_attribute

**Comment by aheiss1** [comment]
Hey,
Glad to hear got up and running. If there is a better way to document in an
effort to help others not run into this issue, please feel free to
contribute a suggestion.

In regards to your current issue, let's start by taking a look at that
'role' object and see if it indeed includes the 'allowed_cas' attribute?
Any ideas there?

Regards,
Alex

**Comment by maxr786** [comment]
I will contribute a suggestion. I have an AD group named cas_admins it has 3 attributes 
casAttribute = production,lower (multivalued, case-insensitive string Active Directory Attribute)
casGroupRole = ca-role (singlevalued, case-insensitive string Active Directory Attribute)
casPrincipleAttribute = permit-agent-forwarding,permit-X11-forwarding (multivalued, case-insensitive string Active Directory Attribute)
The user maxr is a member of cas_admins group 

In my config.json I have the following:
"role_attribute": "casGroupRole",
  "role_description": "description",
  "ca_attribute": "casAttribute",
  "principal_attribute": "casPrincipleAttribute",

**Comment by aheiss1** [comment]
Thanks so much man.

This is much clearer now that you have supplied configs and other info
there.  Please allow me to note, my understanding of ldap, intent and
purpose of this code is not great.  Have you of the BLESS project btw?

I would need to better understand what is being returned from the remote
call, and if that sorta crazy parsing parsses well enough for the code
later on where uyou are currently experiencing the are hitting this issue.

IF you think it's worthwhile, any chance you could send that exact response
to us?   And/Or  what the resulting  parsed object structure looks like?

I appreciate your commitment to improve the docs based on your issues here.

Best,
Alex

**Comment by aheiss1** [comment]
That BLESS meant this, earlier ws this project :
https://github.com/Netflix/bless   It seemed similar to this, and updated
much more recently.  I;d be interested to see if that fits the same use
cases here.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
